### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by amal-khailtash** [mikeshultz/xsd2pgsql#1]
Hi, I am trying to see if I can convert http://accellera.org/images/xmlschema/ipxact/1685-2014/catalog.xsd into pgsql (if it is possible) and I get the following error:

$ python2 xsd2pgsql/xsd2pgsql.py catalog.xsd
Traceback (most recent call last):
  File "xsd2pgsql/xsd2pgsql.py", line 267, in <module>
    result = look4element(XMLS, xsd, pg_normalize(f.name.split('.')[0]), fail=args.failOnBadType, normalize=norm)
  File "xsd2pgsql/xsd2pgsql.py", line 123, in look4element
    rez = look4element(ns, x, x.get('name') or parent, recurse_level + 1, fail=fail)
  File "xsd2pgsql/xsd2pgsql.py", line 151, in look4element
    rez = look4element(ns, x, x.get('name') or parent, recurse_level + 1, fail=fail)
  File "xsd2pgsql/xsd2pgsql.py", line 155, in look4element
    rez = look4element(ns, x, x.get('name') or parent, recurse_level + 1, fail=fail)
  File "xsd2pgsql/xsd2pgsql.py", line 144, in look4element
    cols += ''
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

Any ideas?

**Comment by mikeshultz** [comment]
I have good news and bad news.

# Good news: 

I fixed the bug.

# Bad news: 

The script in its current state will not convert the xsd as you are hoping because it's entirely built with custom XML types, and this doesn't parse namespaces.  You can alter `USER_TYPES` in the script to include translations from one XML type to a PostgreSQL type.  For instance...

    USER_TYPES = { 
        'ipxact:stringURIExpression': 'varchar',
    }

That might work for what you need but I'm not even sure most of these XML types have postgres equivalents that make sense.

**Comment by amal-khailtash** [comment]
I am adding the missing types, but it would be nice if they are reported as warnings if the script cannot find proper types for them.  As is, I need to go and find them all manually.

Regards,
-- Amal

**Comment by amal-khailtash** [comment]
On second thought, all these should be automatic.  I mean the stringURIExpression is defined as:

```
    <xs:complexType name="stringURIExpression">
        <xs:annotation>
            <xs:documentation>IP-XACT URI, like a standard xs:anyURI except that it can contain environment variables in the ${ } form, to be replaced by their value to provide the underlying URI</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
          <xs:extension base="ipxact:complexBaseExpression"/>
        </xs:simpleContent>
    </xs:complexType>
```

Which is based on ipxact:complexBaseExpression:

```
    <xs:complexType name="complexBaseExpression">
        <xs:annotation>
            <xs:documentation>Represents the base-type for an expressions.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
          <xs:extension base="ipxact:simpleBaseExpression">
            <xs:attributeGroup ref="ipxact:any.att"/>
          </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
```

Which is based on ipxact:simpleBaseExpression that is defined as a xs:string:

```
    <xs:simpleType name="simpleBaseExpression">
        <xs:annotation>
            <xs:documentation>Represents the base-type for an expressions, it forces a non whitespace value to be specified.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
          <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
```

I think custom types should all be defined in these schema and they are complete.

Regards,
-- Amal

**Comment by amal-khailtash** [comment]
I forgot to mention that those are defined in other XSD files:  "autoConfigure.xsd  catalog.xsd  commonStructures.xsd  fileType.xsd  identifier.xsd  simpleTypes.xsd  subInstances.xsd  xml.xsd"

simpleTypes.xsd defines most of the types.
